[package]
name = "llm-bedrock"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
aws-config = { version = "1.12.0", features = ["behavior-version-latest"] }
aws-sdk-bedrockruntime = "1.146.0"
aws-smithy-types = "1.8.1"
futures = { workspace = true }
llm-core = { version = "0.1.0", path = "../llm-core" }
serde_json = { workspace = true }
tracing = "0.1.44"

[dev-dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.53.1", features = ["macros", "rt"] }
